Análise de transações financeiras com NumPy
A biblioteca NumPy é uma ferramenta amplamente utilizada na área financeira para a análise de grandes conjuntos de dados, principalmente na detecção de fraudes bancárias. Como analista de dados de uma instituição financeira, você foi designado para analisar transações financeiras a fim de identificar possíveis fraudes. A instituição coleta os dados das transações realizadas e armazena-os em arrays NumPy. Escreva uma função chamada analisa_transacoes, que recebe como entrada um array NumPy de valores de transações e retorna um array NumPy do tipo float64 com as seguintes medidas estatísticas:

Média;
Desvio padrão;
Valor mínimo;
Valor máximo;
Mediana;
Quartis 25% e 75%.
Com essas medidas estatísticas, a instituição poderá identificar possíveis padrões e anomalias nos dados das transações, que podem ser sinais de atividades fraudulentas.

Dica: Utilize as funções disponíveis no NumPy para calcular cada medida estatística.

Exemplo:


transacoes = np.array([100.0, 200.0, 50.0, 300.0, 250.0, 120.0, 80.0, 500.0])

analisa_transacoes(transacoes)

>>> array([200.0, 139.55285736952862, 50.0,  500.0,  160.0, 95.0, 262.5])
Resultados

In [2]:
import numpy as np
def analisa_transacoes(arr: np.ndarray) -> np.ndarray:
	pass

Média de Avaliações de Jogos Eletrônicos Usando Numpy
Você é um analista de dados em uma empresa de jogos eletrônicos e recebeu uma tarefa para analisar as notas de avaliação de jogos de um banco de dados. As notas de avaliação são armazenadas em um array numpy, uma biblioteca do Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas. Uma das vantagens do numpy em relação às listas é que as operações em arrays são mais eficientes computacionalmente, permitindo lidar com grandes quantidades de dados de forma mais rápida. Você precisa calcular a média das notas para ter uma ideia da satisfação dos jogadores com os jogos. Para isso, você vai criar uma função chamada media_avaliacao, que recebe como argumento um array do tipo numpy e retorna um único valor float com a média.

Exemplo:


avaliacoes = np.array([8.5, 7.9, 9.0, 8.8, 8.2])

media_array(avaliacoes)

>>> 8.48


In [3]:
def media_avaliacao(arr: np.ndarray) -> float:
	pass

Criação de uma Matriz Identidade Usando NumPy
No processamento digital de imagens, é comum utilizar matrizes para representar imagens e aplicar operações matemáticas sobre elas. Uma operação comum é a multiplicação de uma matriz por um escalar, que pode ser usado para ajustar o brilho ou a intensidade de cores de uma imagem. O NumPy é uma biblioteca do Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas.

Nesse contexto, crie uma função chamada cria_matriz_identidade que receba dois parâmetros: o tamanho da matriz (n) e o fator de multiplicação (m). A função deve retornar uma matriz identidade de tamanho n x n multiplicada pelo fator m, representada como um array numpy.

Assinatura da função: cria_matriz_identidade(n:int, m:float) -> np.ndarray

Exemplo:


cria_matriz_identidade(3, 2)

>>> array([[2., 0., 0.],
           [0., 2., 0.],
           [0., 0., 2.]])

In [4]:
def cria_matriz_identidade(n:int, m:float) -> np.ndarray:
	pass

Cálculo da soma dos elementos de cada coluna em uma matriz usando NumPy
O processamento digital de imagens é uma área que utiliza técnicas computacionais para processar e analisar imagens digitais. Uma das bibliotecas utilizadas nessa área é o NumPy, uma biblioteca Python que permite trabalhar com matrizes multidimensionais e oferece diversas funções e operações matemáticas.

Suponha que você seja um desenvolvedor de software de processamento digital de imagens e foi designado para criar uma função que calcule a soma dos elementos de cada coluna de uma matriz de entrada. A matriz de entrada pode ter qualquer tamanho e é armazenada como um array NumPy.

Assinatura da função: soma_colunas(matriz: np.ndarray) -> np.ndarray

Exemplo:


matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

soma = soma_colunas(matriz)

>>> array([12, 15, 18])

In [5]:
def soma_colunas(matriz: np.ndarray) -> np.ndarray:
	pass

Criação de DataFrame Pandas para Apoio a Planejamento de Dieta
Suponha que você esteja desenvolvendo um sistema para apoio a planejamento de dieta, que tem como objetivo auxiliar as pessoas a atingirem seus objetivos de saúde por meio de uma alimentação equilibrada. Uma das funcionalidades desse sistema é o registro das informações pessoais dos usuários, tais como nome, idade, sexo, altura e peso.

Para armazenar essas informações, você pode utilizar a biblioteca pandas do Python, que permite trabalhar com tabelas de dados (DataFrames). Pandas é uma biblioteca Python de código aberto que fornece ferramentas de análise e manipulação de dados de forma rápida e eficiente. O Pandas permite trabalhar com dados em formato de tabela, chamados de DataFrames, com colunas de tipos diferentes, além de oferecer funcionalidades para indexação, agregação, seleção, filtragem e visualização dos dados. Com essa biblioteca, é possível realizar tarefas de limpeza, transformação e modelagem de dados, sendo uma ferramenta muito útil em áreas como ciência de dados, finanças, economia, entre outras.

Crie uma função chamada cria_dataframe que receba uma lista contendo as informações de nome, idade, sexo, altura e peso de 
�
n pessoas e retorne um DataFrame com essas informações.

Assinatura da função: cria_dataframe(lista: list) -> pd.DataFrame

Exemplo:

dados = [["Maria", 30, "F", 1.65, 65.0], 
         ["João", 25, "M", 1.75, 80.0], 
         ["Ana", 40, "F", 1.70, 70.0], 
         ["Pedro", 20, "M", 1.80, 75.0], 
         ["Lúcia", 35, "F", 1.60, 55.0]]

cria_dataframe(dados)

>>> 
     Nome  Idade Sexo  Altura  Peso
0   Maria     30    F    1.65  65.0
1    João     25    M    1.75  80.0
2     Ana     40    F    1.70  70.0
3   Pedro     20    M    1.80  75.0
4   Lúcia     35    F    1.60  55.0

In [6]:
def soma_colunas(matriz: np.ndarray) -> np.ndarray:
	pass

Cálculo da Imagem Integral de uma Matriz de Pixels Utilizando NumPy em Processamento de Imagens
Você é um cientista de dados de uma empresa de tecnologia que está desenvolvendo um algoritmo de detecção de bordas em imagens digitais. Para implementar o algoritmo, é necessário calcular a imagem integral da imagem original.

Imagem integral é um conceito muito utilizado no processamento de imagens para acelerar o cálculo de operações como filtros, detecção de bordas e reconhecimento de objetos. Ela consiste em uma matriz que armazena a soma acumulada dos pixels de uma imagem em todas as posições à esquerda e acima de um determinado pixel. Dessa forma, o valor de um determinado retângulo na imagem pode ser calculado em tempo constante, independente do tamanho do retângulo. A imagem integral é amplamente utilizada em aplicações de visão computacional, como detecção de faces e análise de objetos em tempo real.

A equação matemática que define a imagem integral é:

Alt \mathrm{I}(x,y) = \sum_{i=0}^{x}\sum_{j=0}^{y} \mathrm{img}(i,j)

Onde I(x,y) é o valor da imagem integral na posição (x,y) e img(x,y) é o valor da imagem original na mesma posição. A imagem integral é usada em processamento de imagens para calcular a soma dos pixels em uma região retangular da imagem de forma eficiente.

Escreva uma função chamada "calcula_imagem_integral" que recebe como entrada uma matriz numpy e retorna outra matriz numpy com a imagem integral correspondente.

Assinatura da função: calcula_imagem_integral(imagem: np.ndarray) -> np.ndarray

Exemplo:


imagem = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
imagem_integral = calcula_imagem_integral(imagem)

>>> array([[1 , 3 , 6 ],
           [5 , 12, 21],
           [12, 27, 45]])

In [11]:
def calcula_imagem_integral(imagem: np.ndarray) -> np.ndarray:
	pass

Cálculo do Índice de Massa Corporal (IMC) em um Dataframe
Você é um nutricionista e precisa criar uma ferramenta para calcular o Índice de Massa Corporal (IMC) de seus pacientes. Para isso, você pode utilizar a biblioteca Pandas do Python. Ela é uma biblioteca Python de código aberto que fornece ferramentas de análise e manipulação de dados de forma rápida e eficiente. O Pandas permite trabalhar com dados em formato de tabela, chamados de DataFrames, com colunas de tipos diferentes, além de oferecer funcionalidades para indexação, agregação, seleção, filtragem e visualização dos dados. Com essa biblioteca, é possível realizar tarefas de limpeza, transformação e modelagem de dados, sendo uma ferramenta muito útil em áreas como ciência de dados, finanças, economia, entre outras.

Escreva uma função chamada calcula_imc que receba um DataFrame pandas contendo as informações de nome, idade, sexo, altura e peso de um paciente, calcule o IMC e adicione uma nova coluna no DataFrame contendo o resultado do cálculo. Em seguida, a função deve retornar o DataFrame modificado.

In [10]:
import pandas as pd

def calcula_imc(df: pd.DataFrame) -> pd.DataFrame:
	pass

Concatenação de Arrays Numpy para Análise de Vendas em Diferentes Regiões
Você é um analista de dados em uma empresa de vendas online e recebeu uma tarefa para analisar as vendas de um determinado produto em diferentes regiões do país. As informações de vendas são armazenadas em dois arrays numpy, um com as vendas da região Sul e outro com as vendas da região Norte. O numpy é uma biblioteca do Python utilizada para trabalhar com matrizes e arrays multidimensionais de forma eficiente, que oferece diversas funções e operações para facilitar a manipulação desses objetos. Uma das vantagens do numpy em relação às listas do Python é a velocidade e eficiência nas operações com arrays. Você precisa concatenar os dois arrays para ter uma visão geral das vendas do produto em todo o país. Para isso, você vai criar uma função chamada concatena_array, que recebe como argumentos dois arrays do tipo numpy e retorna um único array do tipo numpy concatenando os dois.

Exemplo:


vendas_sul = np.array([100, 150, 200])
vendas_norte = np.array([50, 75, 100])

concatena_array(vendas_sul, vendas_norte)

>>> array([100, 150, 200,  50,  75, 100])

In [9]:
def concatena_array(arr1: np.ndarray, arr2: np.ndarray) -> np.ndarray:
	pass