In [5]:
import numpy as np


mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

In [4]:
mat[(mat==10).any(axis=1)]

array([[ 1, 10]])

In [12]:
mat[(mat==10).any(axis=0)]

array([[20, 30]])

In [6]:
mat[:, (mat > 5).all(axis=0)]

array([[10],
       [30]])

In [11]:
mat[:, (mat==10).any(axis=0)]

array([[10],
       [30]])

In [14]:
new_mat = np.array([1, 2, 4, 5, 7, 8]).reshape(3, 2) 
new_mat

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
(new_mat <8).all(axis=1) # ele esmaga as colunas em uma para achar aquelas que sao true e false

# o eixo que eu passo e aquele que eu estou esmagando 


array([ True,  True, False])

In [17]:
(new_mat == 5).any(axis=0) # esmaga verticalmente


array([False,  True])

In [18]:
mat

array([[ 1, 10],
       [20, 30]])

In [19]:
(mat==10).any(axis=0)

array([False,  True])

In [23]:
mask = (mat == 1) | (mat >= 20)
mat[mask]

array([ 1, 20, 30])

In [25]:
mat[~ mask]

array([10])

In [28]:
np.where(mat != mask)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [29]:
mat

array([[ 1, 10],
       [20, 30]])

In [30]:
np.zeros((2, 3)) # O argumento é o formato do ndarray resultante.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [33]:
np.ones((4, 2, 2)) * 2

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [34]:
np.full((2, 2), 33)

array([[33, 33],
       [33, 33]])

In [35]:
np.full((2, 2), 'oi')

array([['oi', 'oi'],
       ['oi', 'oi']], dtype='<U2')

In [36]:
np_mat = np.array([[1, 2,  3,  4,  5,  6,  7], 
                       [8, 9, 10, 11, 12, 13, 14]])

In [40]:
np.full_like(np_mat, 3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [43]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 7)
r1

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3])

In [46]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 5, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
arr = np.array([[1, 2, 3]])
r2 = np.repeat(arr, 4, axis=1)
r2

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [48]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0, 11, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [50]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [51]:
np.linspace(3, 7, num=10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [52]:
np.linspace(3, 7, num=20)

array([3.        , 3.21052632, 3.42105263, 3.63157895, 3.84210526,
       4.05263158, 4.26315789, 4.47368421, 4.68421053, 4.89473684,
       5.10526316, 5.31578947, 5.52631579, 5.73684211, 5.94736842,
       6.15789474, 6.36842105, 6.57894737, 6.78947368, 7.        ])

In [53]:
np.random.random_sample((4, 2)) # O argumento é o formato do array resultante.

array([[0.80806371, 0.88002352],
       [0.51825042, 0.90137791],
       [0.63237883, 0.52387162],
       [0.36545663, 0.91555221]])

In [55]:
np.random.rand(4, 2)*1000

array([[944.37855591, 323.03572047],
       [ 26.90149655, 952.38068578],
       [580.11496402, 374.22714337],
       [893.99525684, 549.26338922]])

In [56]:
np.random.randint(7, size=(3, 3)) 

array([[3, 3, 3],
       [2, 4, 2],
       [0, 4, 0]])

In [58]:
np.random.randint(100, size=(5, 3)) 

array([[83, 86, 87],
       [51, 11,  3],
       [60, 14, 65],
       [28, 94, 25],
       [86, 78, 33]])

In [59]:
np.random.randint(5, high=10, size=10)

array([5, 5, 5, 6, 8, 8, 5, 9, 7, 6])

In [60]:
np.random.randint(5, high=73129, size=132)

array([ 9748, 67357, 41349, 33774, 12328, 26173,  1022, 25980, 30487,
       67725, 18441, 19720, 46508, 68352, 63986, 63769, 24835, 31743,
       57901, 11139, 70650, 41229, 47962, 50386,  2641, 25466, 17009,
       63073, 53280,  4197, 49044,  2488, 37167, 29624, 21273, 26254,
       51819, 69695, 63034, 35204, 22326, 39952, 33988,   425, 19946,
       49480,  7753, 67152, 37455,  9419, 37714, 19388, 39813, 10111,
       59084, 50417, 11068, 22873, 54487, 27031, 51412,  5666, 44610,
       58711, 50196, 37311,  3788, 14026, 55625, 66032, 52089, 62984,
       23832, 49376, 43563, 27428, 40015, 32385, 23970, 46736, 51532,
       28855, 51245, 23423, 37768, 20572, 54760, 53999, 64804,  6709,
       52527, 52556, 33523, 50092, 44370, 22868,  8327, 35897, 61049,
       57413, 60467, 38034, 12643, 26432, 28229, 47277, 21026, 49584,
       29835, 55677, 32328, 27536, 44460, 18796,  3250, 49030, 59069,
       52323, 32388, 31634,  7771, 51004, 43091, 42958, 15503, 37922,
       31316, 31946,