In [2]:
import numpy as np


mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

array([[ 1, 10],
       [20, 30]])

In [4]:
mat[(mat==10).any(axis=1)]

array([[ 1, 10]])

In [12]:
mat[(mat==10).any(axis=0)]

array([[20, 30]])

In [6]:
mat[:, (mat > 5).all(axis=0)]

array([[10],
       [30]])

In [11]:
mat[:, (mat==10).any(axis=0)]

array([[10],
       [30]])

In [14]:
new_mat = np.array([1, 2, 4, 5, 7, 8]).reshape(3, 2) 
new_mat

array([[1, 2],
       [4, 5],
       [7, 8]])

In [15]:
(new_mat <8).all(axis=1) # ele esmaga as colunas em uma para achar aquelas que sao true e false

# o eixo que eu passo e aquele que eu estou esmagando 


array([ True,  True, False])

In [17]:
(new_mat == 5).any(axis=0) # esmaga verticalmente


array([False,  True])

In [18]:
mat

array([[ 1, 10],
       [20, 30]])

In [19]:
(mat==10).any(axis=0)

array([False,  True])

In [23]:
mask = (mat == 1) | (mat >= 20)
mat[mask]

array([ 1, 20, 30])

In [25]:
mat[~ mask]

array([10])

In [28]:
np.where(mat != mask)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [29]:
mat

array([[ 1, 10],
       [20, 30]])

In [30]:
np.zeros((2, 3)) # O argumento é o formato do ndarray resultante.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [33]:
np.ones((4, 2, 2)) * 2

array([[[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.]]])

In [34]:
np.full((2, 2), 33)

array([[33, 33],
       [33, 33]])

In [35]:
np.full((2, 2), 'oi')

array([['oi', 'oi'],
       ['oi', 'oi']], dtype='<U2')

In [36]:
np_mat = np.array([[1, 2,  3,  4,  5,  6,  7], 
                       [8, 9, 10, 11, 12, 13, 14]])

In [40]:
np.full_like(np_mat, 3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [43]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 7)
r1

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3])

In [46]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 5, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
arr = np.array([[1, 2, 3]])
r2 = np.repeat(arr, 4, axis=1)
r2

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [48]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0, 11, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

In [50]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [51]:
np.linspace(3, 7, num=10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [52]:
np.linspace(3, 7, num=20)

array([3.        , 3.21052632, 3.42105263, 3.63157895, 3.84210526,
       4.05263158, 4.26315789, 4.47368421, 4.68421053, 4.89473684,
       5.10526316, 5.31578947, 5.52631579, 5.73684211, 5.94736842,
       6.15789474, 6.36842105, 6.57894737, 6.78947368, 7.        ])

In [53]:
np.random.random_sample((4, 2)) # O argumento é o formato do array resultante.

array([[0.80806371, 0.88002352],
       [0.51825042, 0.90137791],
       [0.63237883, 0.52387162],
       [0.36545663, 0.91555221]])

In [55]:
np.random.rand(4, 2)*1000

array([[944.37855591, 323.03572047],
       [ 26.90149655, 952.38068578],
       [580.11496402, 374.22714337],
       [893.99525684, 549.26338922]])

In [56]:
np.random.randint(7, size=(3, 3)) 

array([[3, 3, 3],
       [2, 4, 2],
       [0, 4, 0]])

In [58]:
np.random.randint(100, size=(5, 3)) 

array([[83, 86, 87],
       [51, 11,  3],
       [60, 14, 65],
       [28, 94, 25],
       [86, 78, 33]])

In [59]:
np.random.randint(5, high=10, size=10)

array([5, 5, 5, 6, 8, 8, 5, 9, 7, 6])

In [60]:
np.random.randint(5, high=73129, size=132)

array([ 9748, 67357, 41349, 33774, 12328, 26173,  1022, 25980, 30487,
       67725, 18441, 19720, 46508, 68352, 63986, 63769, 24835, 31743,
       57901, 11139, 70650, 41229, 47962, 50386,  2641, 25466, 17009,
       63073, 53280,  4197, 49044,  2488, 37167, 29624, 21273, 26254,
       51819, 69695, 63034, 35204, 22326, 39952, 33988,   425, 19946,
       49480,  7753, 67152, 37455,  9419, 37714, 19388, 39813, 10111,
       59084, 50417, 11068, 22873, 54487, 27031, 51412,  5666, 44610,
       58711, 50196, 37311,  3788, 14026, 55625, 66032, 52089, 62984,
       23832, 49376, 43563, 27428, 40015, 32385, 23970, 46736, 51532,
       28855, 51245, 23423, 37768, 20572, 54760, 53999, 64804,  6709,
       52527, 52556, 33523, 50092, 44370, 22868,  8327, 35897, 61049,
       57413, 60467, 38034, 12643, 26432, 28229, 47277, 21026, 49584,
       29835, 55677, 32328, 27536, 44460, 18796,  3250, 49030, 59069,
       52323, 32388, 31634,  7771, 51004, 43091, 42958, 15503, 37922,
       31316, 31946,

In [3]:
np.random.randint(low = 90, high = 100, size=(4,3))

array([[94, 97, 92],
       [99, 95, 94],
       [95, 94, 93],
       [97, 97, 96]])

In [4]:
vec1 = np.array([2., 4., 6., 8.])
vec2 = np.array([1., 2., 3., 4.])
vec1 + vec2 # Soma

array([ 3.,  6.,  9., 12.])

In [5]:
vec1 - vec2 # subtração

array([1., 2., 3., 4.])

In [6]:
vec1 * vec2 # Multiplicação

array([ 2.,  8., 18., 32.])

In [7]:
vec1 / vec2 # Divisão

array([2., 2., 2., 2.])

In [9]:
vec1 ** vec2 # Exponenciação

array([2.000e+00, 1.600e+01, 2.160e+02, 4.096e+03])

In [10]:
vec2 + 2 # Somar

array([3., 4., 5., 6.])

In [11]:
vec2 - 2 # Subtrair

array([-1.,  0.,  1.,  2.])

In [12]:
vec2 * 2 # Multiplicar

array([2., 4., 6., 8.])

In [13]:
vec2 / 2 # Dividir

array([0.5, 1. , 1.5, 2. ])

In [15]:
vec2 ** 2 # Potência (elevar a um número)

array([ 1.,  4.,  9., 16.])

In [16]:
vec2 += 2 # Incrementar
vec2

array([3., 4., 5., 6.])

In [17]:
a = np.array([1, 2, 3])
b = np.array([2, 2])
a * b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [18]:
matrix = np.array([
  [0, 0, 0],
  [10, 10, 10],
  [20, 20, 20],
  [30, 30, 30]
])
matrix

matrix + np.array([1, 2, 3])

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [19]:
matrix * np.array([1, 2, 3])

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [20]:
a = np.array([
  [1, 2, 3, 4],
  [3, 4, 5, 6],
  [7, 8, 9, 10]
])
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [21]:
b = np.array([10, 20, 30, 40])
b

array([10, 20, 30, 40])

In [22]:
a * b

array([[ 10,  40,  90, 160],
       [ 30,  80, 150, 240],
       [ 70, 160, 270, 400]])

In [23]:
c = np.array([10, 20, 30]).reshape(3,1)
c

array([[10],
       [20],
       [30]])

In [24]:
a * c

array([[ 10,  20,  30,  40],
       [ 60,  80, 100, 120],
       [210, 240, 270, 300]])

In [25]:
#Funcoes matematicas

x = np.array([1.24,2,3.89,4])

In [26]:
np.sin(x)

array([ 0.945784  ,  0.90929743, -0.68047257, -0.7568025 ])

In [27]:
np.cos(x)

array([ 0.32479628, -0.41614684, -0.73277355, -0.65364362])

In [28]:
np.pi

3.141592653589793

In [29]:
x = np.array([0, np.pi / 2 , np.pi, 3 * np.pi / 2, 2 * np.pi])
np.sin(x)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [30]:
x = np.array([1, 2, 3, 4])
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
np.e

2.718281828459045

In [32]:
x = np.array([1, 2, 3, 4])
np.e ** x

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [33]:
x = np.linspace(-1, 2, 10)
x

array([-1.        , -0.66666667, -0.33333333,  0.        ,  0.33333333,
        0.66666667,  1.        ,  1.33333333,  1.66666667,  2.        ])

In [34]:
np.exp(x) + np.sin(x)

array([-0.47359154, -0.10495268,  0.38933661,  1.        ,  1.72280712,
        2.56610384,  3.55975281,  4.7656058 ,  6.28989801,  8.29835353])

In [35]:
np.inf > 999999999999999999999999

True

In [36]:
-np.inf < -999999999999999999999999

True

In [37]:
(np.inf + 1) == np.inf

True

In [38]:
np.inf - np.inf

nan

In [39]:
np.array([1]) / np.array([0])

C:\Users\Drac3\AppData\Local\Temp\ipykernel_26460\2758096263.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1]) / np.array([0])


array([inf])

In [40]:
a = np.array([1,2,3,4,5])

In [41]:
a.dtype

dtype('int32')

In [42]:
a[0] = np.nan

ValueError: cannot convert float NaN to integer

In [43]:
a = np.array([np.nan,2,3,4,5])

In [44]:
a.dtype

dtype('float64')

In [45]:
np.float64(0)/np.float64(0)

C:\Users\Drac3\AppData\Local\Temp\ipykernel_26460\3333974617.py:1: RuntimeWarning: invalid value encountered in scalar divide
  np.float64(0)/np.float64(0)


nan

In [48]:
a[1]

2.0

In [49]:
np.NaN + 44

nan

In [50]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 2, 3])

In [51]:
vec1.dot(vec2)

15

In [52]:
vec1 @ vec2

15

In [53]:
matrix = np.array([
  [1, 1, 1],
  [1, 2, 3],
  [1, 1, 1]
])
vec2 = np.array([2, 2, 3])

In [54]:
matrix.dot(vec2)

array([ 7, 15,  7])

In [55]:
matrix @ vec2

array([ 7, 15,  7])

In [56]:
matrix1 = np.array([
  [1, 1, 1],
  [1, 2, 3],
  [1, 1, 1]
])
matrix2 = np.array([
  [1, 1, 1],
  [1, 1, 1],
  [1, 1, 1]
])
matrix1.dot(matrix2)

array([[3, 3, 3],
       [6, 6, 6],
       [3, 3, 3]])

In [57]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
matrix1

array([[1, 1, 1],
       [1, 2, 3],
       [1, 1, 1]])

In [59]:
matrix1 @ np.identity(3)

array([[1., 1., 1.],
       [1., 2., 3.],
       [1., 1., 1.]])

In [60]:
a = np.array([1,2,3,4,5,6]).reshape((3,2))
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
np.transpose(a)

array([[1, 3, 5],
       [2, 4, 6]])

In [62]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [63]:
a = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
np.linalg.det(a)

0.0

In [65]:
c = np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
np.linalg.det(c)

1.0

In [67]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
np.min(stats)

1

In [69]:
np.max(stats)

6

In [70]:
np.min(stats, axis=0)

array([1, 2, 3])

In [71]:
np.min(stats, axis=1)

array([1, 4])

In [72]:
np.sum(stats)

21

In [73]:
np.sum(stats, axis=1)

array([ 6, 15])

In [74]:
np.mean(stats)

3.5

In [75]:
np.median(stats)

3.5

In [76]:
a = np.array([1,2,3,4,7,20,300])
a

array([  1,   2,   3,   4,   7,  20, 300])

In [77]:
np.mean(a)

48.142857142857146

In [78]:
np.median(a)

4.0

In [79]:
valores = np.array([40000, 60000, 35000, 38000, 280000])
valores

array([ 40000,  60000,  35000,  38000, 280000])

In [80]:
np.mean(valores)

90600.0

In [81]:
np.median(valores)

40000.0