In [1]:
import numpy as np 

a = np.array([1, 2, 3])

In [2]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.array([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
vetor = np.array([1,2,3,4,5,6,7])
vetor.dtype

dtype('int32')

In [5]:
vetor = np.array([1.3,1.6,3.4,4.4,4,2,3])
vetor.dtype

dtype('float64')

In [6]:
vetor = np.array([1.3,'ABACATE',3.4,4.4,4,2,3])
vetor.dtype

dtype('<U32')

In [8]:
vetor = np.array([1.2,3.4,5,2,6,2], dtype = np.int32)
vetor.dtype

dtype('int32')

In [9]:
vetor.ndim

1

In [11]:
a16 = np.array([1,2,3], dtype=np.int16)
a16

array([1, 2, 3], dtype=int16)

In [12]:
a16.itemsize

2

In [15]:
a16 = np.array([1,2,3,4], dtype=np.int16)
a16

array([1, 2, 3, 4], dtype=int16)

In [16]:
a16.itemsize

2

In [17]:
a = np.array([1.0,2.0,3.0])
a.dtype

dtype('float64')

In [18]:
b = a.astype('int32').copy() # nao precisa usar o copy pq nao altera o variaval original

In [19]:
b.dtype

dtype('int32')

In [20]:
a.dtype

dtype('float64')

In [21]:
c = a.astype('int32')

In [23]:
c.dtype

dtype('int32')

In [26]:
py_mat = [
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
]
py_mat

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]

In [27]:
np_mat = np.array( [
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [30]:
py_mat[1][5]

13

In [28]:
np_mat[1][5]

13

In [29]:
np_mat[1,5]

13

In [31]:
py_mat[0][-1]

7

In [32]:
np_mat[0,-1]

7

In [33]:
np_mat[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
np_mat[:,0]

array([1, 8])

In [36]:
#slicing 

np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [40]:
np_mat[:,:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [41]:
np_mat[0,2:4]

array([3, 4])

In [42]:
np_mat[1,1:6]

array([ 9, 10, 11, 12, 13])

In [43]:
np_mat[1,1:6:2]

array([ 9, 11, 13])

In [44]:
np_mat[1,2:-2]

array([10, 11, 12])

In [46]:
np_mat[1,5]= 99
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 99, 14]])

In [50]:
np_mat[:,3] = 100
np_mat

array([[  1,   2,   3, 100,   5,   6,   7],
       [  8,   9,  10, 100,  12,  99,  14]])

In [51]:
np_mat[:,2:4] = -33
np_mat

array([[  1,   2, -33, -33,   5,   6,   7],
       [  8,   9, -33, -33,  12,  99,  14]])

In [52]:
np_mat = np.array( [
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [53]:
a = np_mat[:, -4:-2]

In [54]:
a

array([[ 4,  5],
       [11, 12]])

In [57]:
a[:,:]=10
a

array([[10, 10],
       [10, 10]])

In [58]:
np_mat

array([[ 1,  2,  3, 10, 10,  6,  7],
       [ 8,  9, 10, 10, 10, 13, 14]])

In [59]:
a = np.array(['a','b','c','d','e','f','g','h'])
a

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='<U1')

In [60]:
indices_de_interesse = [0,3,4,6,-1]
a[indices_de_interesse]

array(['a', 'd', 'e', 'g', 'h'], dtype='<U1')

In [63]:
a.reshape((2,4))

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h']], dtype='<U1')

In [67]:
a = np.array(['a','b','c','d','e','f','g','h', 'i'])


In [71]:
a = a.reshape((3,3))


In [72]:
a[[0,0,2], [1,2,2]]

array(['b', 'c', 'i'], dtype='<U1')

In [76]:
a = np.array(['a','b','c','d','e','f','g','h', 'i'])


In [77]:
a[[1,4,7]]

array(['b', 'e', 'h'], dtype='<U1')

In [78]:
a[[False, True, False, False, True, False, False, True, False]]

array(['b', 'e', 'h'], dtype='<U1')

In [79]:
a = np.array(['a','b','c','d','e','f','g','h', 'i'])
a[a>'f']

array(['g', 'h', 'i'], dtype='<U1')

In [80]:
a[a=='f']

array(['f'], dtype='<U1')

In [81]:
np_mat = np.array( [
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])
np_mat

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [83]:
np_mat[np_mat>=4]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
[True if i>=4 else False for i in range(0,len(a))]

[False, False, False, False, True, True, True, True, True]

In [85]:
a[[True if i>=4 else False for i in range(0,len(a))]]

array(['e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [86]:
a

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [89]:
a[a >= 'g']

array(['g', 'h', 'i'], dtype='<U1')

In [90]:
np.where(a >= 'g')

(array([6, 7, 8], dtype=int64),)

In [93]:
a = a.reshape((3,3))
a

array([['a', 'b', 'c'],
       ['d', 'e', 'f'],
       ['g', 'h', 'i']], dtype='<U1')

In [94]:
np.where( a >= 'g')

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [95]:
a[a >= 'h' or a <= 'b']
# or = |
# and = &

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [97]:
a[(a >= 'h') | (a <= 'b')]

array(['a', 'b', 'h', 'i'], dtype='<U1')

In [98]:
a[(a >= 'h') & (a <= 'b')]

array([], dtype='<U1')